services:
  mysql:
    image: mysql:8.0.32
    container_name: gbpm-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    networks:
      - gbpm-network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: gbpm-phpmyadmin
    hostname: gbpm-phpmyadmin
    ports:
      - "18899:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=123456
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gbpm-network

  redis:
    image: redis:6.2
    container_name: gbpm-redis
    restart: always
    hostname: gbpm-redis
    privileged: true
    ports:
      - "16379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - gbpm-network

#  redis-admin:
#    image: spryker/redis-commander:0.8.0
#    container_name: gbpm-redis-admin
#    hostname: gbpm-redis-admin
#    restart: always
#    ports:
#      - "18081:8081"
#    environment:
#      - REDIS_HOSTS=local:redis:6379
#      - HTTP_USER=admin
#      - HTTP_PASSWORD=admin
#      - LANG=C.UTF-8
#      - LANGUAGE=C.UTF-8
#      - LC_ALL=C.UTF-8
#    depends_on:
#      redis:
#        condition: service_healthy
#    networks:
#      - gbpm-network

  rabbitmq:
    image: registry.cn-hangzhou.aliyuncs.com/xfg-studio/rabbitmq:3.12.9
    container_name: gbpm-rabbitmq
    restart: always
    hostname: gbpm-rabbitmq
    ports:
      - "15673:5672"
      - "15674:15672"
    networks:
      - gbpm-network

  frpc:
    image: fatedier/frpc:v0.60.0
    container_name: gbpm-frpc
    restart: always
    volumes:
      - ./frp/frpc.toml:/etc/frp/frpc.toml:ro
    command: ["-c", "/etc/frp/frpc.toml"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gbpm-network

networks:
  gbpm-network:
    driver: bridge
